BEGIN;

CREATE TABLE IF NOT EXISTS app.schema_migrations (
  version integer PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION app.current_account_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT current_setting('openmatch.account_id')::uuid
$$;

CREATE TABLE IF NOT EXISTS app.account_state (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  key text NOT NULL,
  value text NOT NULL,
  PRIMARY KEY (account_id, key)
);
CREATE TABLE IF NOT EXISTS app.account_decisions (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id text NOT NULL,
  decision text NOT NULL CHECK (decision IN ('interested','passed')),
  created_at text NOT NULL,
  PRIMARY KEY (account_id, profile_id)
);
CREATE TABLE IF NOT EXISTS app.account_connections (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  id text NOT NULL,
  profile_id text NOT NULL,
  created_at text NOT NULL,
  closed_at text,
  muted smallint NOT NULL DEFAULT 0 CHECK (muted IN (0,1)),
  meeting_preference text NOT NULL DEFAULT 'not_asked'
    CHECK (meeting_preference IN ('not_asked','not_yet','open_to_plan')),
  PRIMARY KEY (account_id, id),
  UNIQUE (account_id, profile_id)
);
CREATE TABLE IF NOT EXISTS app.account_messages (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  connection_id text NOT NULL,
  sender_id text NOT NULL,
  text text NOT NULL,
  created_at text NOT NULL,
  delivery_event_id text,
  PRIMARY KEY (account_id, id),
  UNIQUE (account_id, delivery_event_id),
  FOREIGN KEY (account_id, connection_id)
    REFERENCES app.account_connections(account_id, id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS app.account_blocks (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (account_id, profile_id)
);
CREATE TABLE IF NOT EXISTS app.account_reports (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  profile_id text NOT NULL,
  reason text NOT NULL,
  details text NOT NULL,
  status text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (account_id, id)
);
CREATE TABLE IF NOT EXISTS app.account_report_updates (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  report_id bigint NOT NULL,
  kind text NOT NULL
    CHECK (kind IN ('additional_context','correction','withdrawal_request')),
  details text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (account_id, id),
  FOREIGN KEY (account_id, report_id)
    REFERENCES app.account_reports(account_id, id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS app.account_saved_introductions (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (account_id, profile_id)
);
CREATE TABLE IF NOT EXISTS app.account_preference_observations (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id text NOT NULL,
  interested smallint NOT NULL CHECK (interested IN (0,1)),
  factors_json text NOT NULL,
  selection_probability double precision NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (account_id, profile_id)
);
CREATE TABLE IF NOT EXISTS app.account_processed_account_events (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  event_id text NOT NULL,
  processed_at text NOT NULL,
  PRIMARY KEY (account_id, event_id)
);
CREATE TABLE IF NOT EXISTS app.account_connection_outcomes (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  connection_id text NOT NULL,
  kind text NOT NULL
    CHECK (kind IN ('met_in_person','wanted_second_date','relationship_started','relationship_ended')),
  recorded_at text NOT NULL,
  PRIMARY KEY (account_id, connection_id, kind),
  FOREIGN KEY (account_id, connection_id)
    REFERENCES app.account_connections(account_id, id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS app.account_data_model_records (
  account_id uuid NOT NULL DEFAULT app.current_account_id() REFERENCES auth.users(id) ON DELETE CASCADE,
  id text NOT NULL,
  family text NOT NULL
    CHECK (family IN ('behavior','match_funnel','communication_metadata','activity','profile_media','profile_quality','pair_feature','context','exposure_audit','prediction','recommendation','feedback','safety')),
  subject_id text,
  occurred_at text NOT NULL,
  consent_notice_version text,
  payload_json text NOT NULL,
  PRIMARY KEY (account_id, id)
);
CREATE INDEX IF NOT EXISTS account_data_model_family_time
  ON app.account_data_model_records(account_id, family, occurred_at);
CREATE INDEX IF NOT EXISTS account_data_model_subject
  ON app.account_data_model_records(account_id, subject_id)
  WHERE subject_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS app.sqlite_migration_audit (
  account_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  source_sha256 text NOT NULL,
  row_counts jsonb NOT NULL,
  migrated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE VIEW app.state WITH (security_barrier=true) AS
  SELECT key,value FROM app.account_state
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.decisions WITH (security_barrier=true) AS
  SELECT profile_id,decision,created_at FROM app.account_decisions
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.connections WITH (security_barrier=true) AS
  SELECT id,profile_id,created_at,closed_at,muted,meeting_preference
  FROM app.account_connections WHERE account_id=app.current_account_id()
  WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.messages WITH (security_barrier=true) AS
  SELECT id,connection_id,sender_id,text,created_at,delivery_event_id
  FROM app.account_messages WHERE account_id=app.current_account_id()
  WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.blocks WITH (security_barrier=true) AS
  SELECT profile_id,created_at FROM app.account_blocks
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.reports WITH (security_barrier=true) AS
  SELECT id,profile_id,reason,details,status,created_at FROM app.account_reports
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.report_updates WITH (security_barrier=true) AS
  SELECT id,report_id,kind,details,created_at FROM app.account_report_updates
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.saved_introductions WITH (security_barrier=true) AS
  SELECT profile_id,created_at FROM app.account_saved_introductions
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.preference_observations WITH (security_barrier=true) AS
  SELECT profile_id,interested,factors_json,selection_probability,created_at
  FROM app.account_preference_observations
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.processed_account_events WITH (security_barrier=true) AS
  SELECT event_id,processed_at FROM app.account_processed_account_events
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.connection_outcomes WITH (security_barrier=true) AS
  SELECT connection_id,kind,recorded_at FROM app.account_connection_outcomes
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;
CREATE OR REPLACE VIEW app.data_model_records WITH (security_barrier=true) AS
  SELECT id,family,subject_id,occurred_at,consent_notice_version,payload_json
  FROM app.account_data_model_records
  WHERE account_id=app.current_account_id() WITH LOCAL CHECK OPTION;

INSERT INTO app.schema_migrations(version) VALUES (1)
ON CONFLICT (version) DO NOTHING;

COMMIT;
